### ISSUE TITLE
CoinSpend: Accumulator witness does not verify

### ISSUE THREAD

**Issue by bogec** [XUEZ/xuez#3]
zXuez coins cannot be converted back at the moment by sending them to yourself regardless of the amount you choose or the Security Level you choose.
The error message is: CoinSpend: Accumulator witness does not verify
Apparently this is a bug as described for Pivx:
https://pivx.freshdesk.com/support/solutions/articles/30000026466-coinspend-accumulator-witness-does-not-verify

**Comment by davembg** [comment]
Did you do this?
In the Privacy tab, set the security to 100 and rescan/reset the the wallet. If not solved, re-open the wallet and ensure the wallet is completely synced.

**Comment by davembg** [comment]
Yes, it’s working now.
zXuez created before block 7000 (I think) are invalid and those funds are lost.
GodFather has a process to restore those funds, and I think most have been resolved.

**Comment by MikeR66c** [comment]
That's what I thought, thanks Dave!
